tor-address:
  name: Network Tor Address
  description: The Tor address for the network interface.
  type: pointer
  subtype: package
  package-id: agora
  target: tor-address
  interface: main
directory:
  name: Directory Path
  description: The path to the directory in File Browser that will be served on your Agora .onion address. For example, a value of "satoshi/files" would tell Agora to look for that directory in File Browser.
  type: string
  pattern: "^(\\.|[a-zA-Z0-9_ -][a-zA-Z0-9_ .-]*|([a-zA-Z0-9_ .-][a-zA-Z0-9_ -]+\\.*)+)(/[a-zA-Z0-9_ -][a-zA-Z0-9_ .-]*|/([a-zA-Z0-9_ .-][a-zA-Z0-9_ -]+\\.*)+)*/?$"
  pattern-description: Must be a valid relative file path
  nullable: false
  default: "agora-files"
